### PR TITLE
Add auto-pagination

### PR DESCRIPTION
**Pull request by neodem**
Adds the ability to handle resistor arrays that span multiple pages

### CODE REVIEW

**Comment by Finomnis** [comment]
In general not a bad idea, I'm not generally opposed to it.

However, here's a couple of things I'd like to change:
- Don't change `main`. It's meant to be as beginner-friendly as possible. It is the only place where manual configuration should take place, and remember that there are a lot of people that have never programmed before that will use this script. It's primarily for the hardware community.
- Don't hard-code `10` as the page size. That's only correct for one type of paper. Instead, use the paper configs to configure it per paper type.
- Don't create multiple PDFs. `reportlab` is perfectly capable of creating multiple pages on a single PDF.
- Your `make_pages` is not quite refined yet; it produces empty pages in some scenarios. You might want to research how to split an array into chunks in python; there is a lot of material out there already. For example: https://www.geeksforgeeks.org/break-list-chunks-size-n-python/

**Comment by neodem** [comment]
Ya def.. 100% great feedback and I agree with all of it. I was just playing around with it and was bummed about the one page limit so I hacked that in 2m and then thought I should share it as a starting point for you..

I will try to make the changes you indicated when I get a few moments though.. 

Thanks for the initial script!

**Comment by Finomnis** [comment]
While you are on it, we might go even one further. As kind of talked about in #7, people don't just want things to auto-distribute on pages, but also on lines. They basically want to just provide a long list of resistors and then they get distributed on pages and lines.

For auto-formatting and readability reasons, I would like to keep it as a 2D array, though.

We could solve both use-cases at the same time by:
- flattening the input array
- distributing it to groups of `width`
- distributing the result to groups of `height
- use that as our rows/pages

We could move all of that into `render_stickers` so it doesn't clutter `main`.
We just have to see how to deal with `render_outlines`. Maybe add a bool parameter to `render_sticker`?

While we are on it, I just realized I hard-coded the sticker count into `render_outlines`. We should fix that and replace it with the paper type specific number you will have to introduce into `PaperConfig` anyway.

**Comment by Finomnis** [comment]
Sorry for the failing 3.6 test ... it seems the action removed 3.6 support. Fixed in #17.

Please merge `main` into your branch to apply the fixes.

**Comment by Finomnis** [comment]
If you're having a hard time, feel free to tell me, I'm glad to give you a helping hand :)

**Review by Finomnis — APPROVED** [review]

**Comment by Finomnis** [comment]
Should now work as you described. Thanks for the suggestion :)

**Pull request merged**
