### PR TITLE
Allow zero ohm resistor

### PR DESCRIPTION
**Pull request by spuder**
There are 0 ohm resistors, however this script currently assumes all resistor values are >=1. If you attempt to generate a 0 ohm resistor it will be skipped. 

```
    resistor_values = [
        [0,         1,          10],
        [100,       1000,       10000],
        [0.1,       0.01,       0.001],
        [200000,    3000000,    40000000],
    ]
 ```

# Before
Screen Shot 2022-11-05 at 6 32 56 PM

# After
Screen Shot 2022-11-05 at 6 30 16 PM

~Note:  Technically [0 ohm resistors](https://en.wikipedia.org/wiki/Zero-ohm_link) have only 1 band instead of 3. However refactoring this script to allow only single band images may be a much larger refactor, which may or may not be worth the effort for this single obscure resistor value.~

## Update: 
Now shows single band. 
Screen Shot 2022-11-06 at 12 05 55 AM

### CODE REVIEW

**Comment by Finomnis** [comment]
Good catch! This change will definitely be merged.

https://www.reichelt.de/widerstand-metallschicht-0-0-ohm-0207-0-6-w-1--metall-0-00-p184962.html

Seems like they exist both with the single stripe as also with the full 5 stripes. It's there an official norm?

**Comment by Finomnis** [comment]
It seems that the most common marking on SMD is "0" or "000", indicating precision. From my first search I very rarely found "R0", this one seems more dominant in schematics, but not in the resistor itself.

**Comment by spuder** [comment]
> Seems like they exist both with the single stripe as also with the full 5 stripes. Is there an official norm?

The through hole ones I own are a single stripe. 

> It seems that the most common marking on SMD is "0" or "000", indicating precision. From my first search I very rarely found "R0", this one seems more dominant in schematics, but not on the resistor itself.

I can change `R0` to `0`

**Comment by Finomnis** [comment]
> I can change `R0` to `0` or `000`. Do you have a preference?

The ones I have seen the most often when browsing through the web were `0` and `000`, so those two are the ones I would display.

I'll do some minor changes and push to your branch, if that's fine.

**Comment by spuder** [comment]
>I'll do some minor changes and push to your branch, if that's fine.

Please do. I'm sure there are many ways to optimize this code.

**Comment by Finomnis** [comment]
After thinking about it some more, I think you were right with the `000` and `0000`, for consistency; it's always 3-digit and 4-digit.

I updated the `Example.pdf` as well to include a `0 Ohm` value.

Give me your thumbs up if you agree with my changes in your code and the current state, then I'll merge.

**Review by Finomnis — APPROVED** [review]

**Comment by spuder** [comment]
Much cleaner, thank you 👍

**Comment by Finomnis** [comment]
Thanks for your contribution :)

**Pull request merged**
